version: 2
jobs:
  build:
    working_directory: /go/src/github.com/shogo82148/go-nginx-oauth2-adapter
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install nginx cmake build-essential ruby openssl libssl-dev zlib1g-dev bison
            sudo chmod -R 777 /var/log/nginx
            sudo chmod -R 777 /var/lib/nginx
            bash ./circle-ci-install-h2o.sh
            make installdeps
      - run:
          name: Test
          command: go build -v && make test
